import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * AdaL CLI Documentation Sidebar
 * 
 * Using autogenerated sidebars that automatically reflect the directory structure
 * and sidebar_position values defined in each markdown file's frontmatter.
 * 
 * Note: build-with-adal/ is commented out to avoid showing duplicate MCP content.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from root docs directory
    },
  ],
};

export default sidebars;
